version: "3"
services: 
    nginx: 
        ports: 
            - "3000:80"

    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_PASSWORD=thanhkhiet
            - MONGO_USER=thanhkhiet
            - SESSION_SECRET=secret
        command: npm run dev

    mongoDb:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=thanhkhiet
            - MONGO_INITDB_ROOT_PASSWORD=thanhkhiet
    